addons:
  - chrome: stable
language: python
cache: pip
python:
  - 2.7
apt:
  packages:
    - chromium-chromedriver
before_install:
  - export PATH="$HOME/bin:$PATH"
install:
  - pip install -r requirements_dev.txt
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - pytest --driver Chrome --driver-path "${HOME}/bin/chromedriver"
