sudo: required
addons:
  - chrome: stable
language: python
cache: pip
python:
  - 2.7
before_install:
  - wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER/chromedriver_linux64.zip
  - mkdir $HOME/chromedriver && unzip /tmp/chromedriver.zip -d $HOME/chromedriver
  - export PATH=$HOME/chromedriver:$PATH
install:
  - pip install -r requirements_dev.txt
script:
  - pytest --driver Chrome
