sudo: yes
addons:
  - chrome: stable
language: python
cache: pip
python:
  - 2.7
apt:
  packages:
    - chromium-chromedriver
before_install:
  - mkdir /tmp/chromedriver
  - wget https://chromedriver.storage.googleapis.com/75.0.3770.140/chromedriver_linux64.zip -O /tmp/chromedriver/chromedriver.zip
  - unzip /tmp/chromedriver/chromedriver.zip -d /tmp/chromedriver
  - chmod 700 /tmp/chromedriver/chromedriver
install:
  - pip install -r requirements_dev.txt
script:
  - pytest --driver Chrome --driver-path /tmp/chromedriver/chromedriver
