addons:
  - chrome: stable
language: python
cache: pip
python:
  - 2.7
apt:
  packages:
    - chromium-chromedriver
install:
  - pip install -r requirements_dev.txt
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
script:
  - pytest --driver Chrome
