sudo: false
language: python
cache:
  - pip
python:
  - 2.7
addons:
  apt:
    packages:
      - google-chrome-stable
env:
  - FLASK_ENV=development
before_install:
  - whereis google-chrome-stable
  - google-chrome-stable --version
  - mkdir /tmp/chromedriver
  - wget https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip -O /tmp/chromedriver/chromedriver.zip
  - unzip /tmp/chromedriver/chromedriver.zip -d /tmp/chromedriver
  - chmod 700 /tmp/chromedriver/chromedriver
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - pip install -r requirements_dev.txt
  - yarn install
script:
  - pytest --driver Chrome --driver-path /tmp/chromedriver/chromedriver
