"""empty message

Revision ID: 249fc39ee89f
Revises: 
Create Date: 2019-02-10 13:26:37.261506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249fc39ee89f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codelist',
    sa.Column('code', sa.UnicodeText(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('country',
    sa.Column('code', sa.UnicodeText(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_order', sa.Integer(), nullable=True),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.Column('domestic_external', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.UnicodeText(), nullable=True),
    sa.Column('budget_code', sa.UnicodeText(), nullable=True),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.Column('acronym', sa.UnicodeText(), nullable=True),
    sa.Column('_type', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codelistcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.UnicodeText(), nullable=True),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.Column('codelist_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codelist_code'], ['codelist.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'codelist_code')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geonames_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.UnicodeText(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.Column('latitude', sa.UnicodeText(), nullable=True),
    sa.Column('longitude', sa.UnicodeText(), nullable=True),
    sa.Column('feature_code', sa.UnicodeText(), nullable=True),
    sa.Column('admin1_code', sa.UnicodeText(), nullable=True),
    sa.Column('admin2_code', sa.UnicodeText(), nullable=True),
    sa.Column('admin3_code', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['country.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_country_code'), 'location', ['country_code'], unique=False)
    op.create_table('maediuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.UnicodeText(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.Column('email_address', sa.UnicodeText(), nullable=True),
    sa.Column('reset_password_key', sa.UnicodeText(), nullable=True),
    sa.Column('pw_hash', sa.String(length=255), nullable=True),
    sa.Column('organisation', sa.UnicodeText(), nullable=True),
    sa.Column('administrator', sa.Boolean(), nullable=True),
    sa.Column('recipient_country_code', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_country_code'], ['country.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_maediuser_recipient_country_code'), 'maediuser', ['recipient_country_code'], unique=False)
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.UnicodeText(), nullable=True),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reporting_org_id', sa.Integer(), nullable=False),
    sa.Column('implementing_org', sa.UnicodeText(), nullable=True),
    sa.Column('recipient_country_code', sa.UnicodeText(), nullable=False),
    sa.Column('dac_sector', sa.UnicodeText(), nullable=True),
    sa.Column('collaboration_type', sa.UnicodeText(), nullable=True),
    sa.Column('finance_type', sa.UnicodeText(), nullable=True),
    sa.Column('tied_status', sa.UnicodeText(), nullable=True),
    sa.Column('flow_type', sa.UnicodeText(), nullable=True),
    sa.Column('aid_type', sa.UnicodeText(), nullable=True),
    sa.Column('activity_status', sa.UnicodeText(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('domestic_external', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_country_code'], ['country.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporting_org_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['maediuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_recipient_country_code'), 'activity', ['recipient_country_code'], unique=False)
    op.create_index(op.f('ix_activity_reporting_org_id'), 'activity', ['reporting_org_id'], unique=False)
    op.create_index(op.f('ix_activity_user_id'), 'activity', ['user_id'], unique=False)
    op.create_table('userorganisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permission_name', sa.UnicodeText(), nullable=True),
    sa.Column('permission_value', sa.UnicodeText(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['maediuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userpermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permission_name', sa.UnicodeText(), nullable=True),
    sa.Column('permission_value', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['maediuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activitycodelistcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('codelist_code_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['codelist_code_id'], ['codelistcode.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'codelist_code_id')
    )
    op.create_table('activityfinances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.UnicodeText(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('transaction_type', sa.UnicodeText(), nullable=True),
    sa.Column('transaction_description', sa.UnicodeText(), nullable=True),
    sa.Column('transaction_value', sa.Float(precision=2), nullable=True),
    sa.Column('finance_type', sa.UnicodeText(), nullable=True),
    sa.Column('aid_type', sa.UnicodeText(), nullable=True),
    sa.Column('provider_org_id', sa.Integer(), nullable=False),
    sa.Column('receiver_org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['provider_org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['receiver_org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activityfinances_activity_id'), 'activityfinances', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activityfinances_transaction_type'), 'activityfinances', ['transaction_type'], unique=False)
    op.create_table('activitylocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activitymilestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('achieved', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'milestone_id')
    )
    op.create_index(op.f('ix_activitymilestone_activity_id'), 'activitymilestone', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activitymilestone_milestone_id'), 'activitymilestone', ['milestone_id'], unique=False)
    op.create_table('activityorganisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'organisation_id', 'role')
    )
    op.create_table('activityresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('result_title', sa.UnicodeText(), nullable=True),
    sa.Column('result_description', sa.UnicodeText(), nullable=True),
    sa.Column('result_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activityresult_activity_id'), 'activityresult', ['activity_id'], unique=False)
    op.create_table('forwardspend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(precision=2), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_currency', sa.UnicodeText(), nullable=True),
    sa.Column('period_start_date', sa.Date(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activityfinancescodelistcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activityfinance_id', sa.Integer(), nullable=False),
    sa.Column('codelist_id', sa.Integer(), nullable=False),
    sa.Column('codelist_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activityfinance_id'], ['activityfinances.id'], ),
    sa.ForeignKeyConstraint(['codelist_code_id'], ['codelistcode.id'], ),
    sa.ForeignKeyConstraint(['codelist_id'], ['codelist.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activityfinance_id', 'codelist_id')
    )
    op.create_table('activityresultindicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('indicator_title', sa.UnicodeText(), nullable=True),
    sa.Column('indicator_description', sa.UnicodeText(), nullable=True),
    sa.Column('baseline_year', sa.Date(), nullable=True),
    sa.Column('baseline_value', sa.UnicodeText(), nullable=True),
    sa.Column('baseline_comment', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['activityresult.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activityresultindicator_result_id'), 'activityresultindicator', ['result_id'], unique=False)
    op.create_table('activityresultindicatorperiod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('target_value', sa.UnicodeText(), nullable=True),
    sa.Column('target_comment', sa.UnicodeText(), nullable=True),
    sa.Column('actual_value', sa.UnicodeText(), nullable=True),
    sa.Column('actual_comment', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['activityresultindicator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activityresultindicatorperiod_indicator_id'), 'activityresultindicatorperiod', ['indicator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activityresultindicatorperiod_indicator_id'), table_name='activityresultindicatorperiod')
    op.drop_table('activityresultindicatorperiod')
    op.drop_index(op.f('ix_activityresultindicator_result_id'), table_name='activityresultindicator')
    op.drop_table('activityresultindicator')
    op.drop_table('activityfinancescodelistcode')
    op.drop_table('forwardspend')
    op.drop_index(op.f('ix_activityresult_activity_id'), table_name='activityresult')
    op.drop_table('activityresult')
    op.drop_table('activityorganisation')
    op.drop_index(op.f('ix_activitymilestone_milestone_id'), table_name='activitymilestone')
    op.drop_index(op.f('ix_activitymilestone_activity_id'), table_name='activitymilestone')
    op.drop_table('activitymilestone')
    op.drop_table('activitylocation')
    op.drop_index(op.f('ix_activityfinances_transaction_type'), table_name='activityfinances')
    op.drop_index(op.f('ix_activityfinances_activity_id'), table_name='activityfinances')
    op.drop_table('activityfinances')
    op.drop_table('activitycodelistcode')
    op.drop_table('userpermission')
    op.drop_table('userorganisation')
    op.drop_index(op.f('ix_activity_user_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_reporting_org_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_recipient_country_code'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_maediuser_recipient_country_code'), table_name='maediuser')
    op.drop_table('maediuser')
    op.drop_index(op.f('ix_location_country_code'), table_name='location')
    op.drop_table('location')
    op.drop_table('codelistcode')
    op.drop_table('organisation')
    op.drop_table('milestone')
    op.drop_table('country')
    op.drop_table('codelist')
    # ### end Alembic commands ###
