"""empty message

Revision ID: 28cc66cf9810
Revises: 91c810ce1b2c
Create Date: 2019-08-25 15:34:31.736027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cc66cf9810'
down_revision = '91c810ce1b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activityresultindicatorperiod") as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), server_default="4", nullable=False))
    with op.batch_alter_table("activityresultindicatorperiod") as batch_op:
        batch_op.alter_column("status", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activityresultindicatorperiod") as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###
