"""empty message

Revision ID: 33302296b8d5
Revises: 4d9408ee62dd
Create Date: 2019-12-10 19:15:58.465908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33302296b8d5'
down_revision = '4d9408ee62dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO role (slug, name) VALUES ('results-data-design','Results data design');")
    op.execute("INSERT INTO role (slug, name) VALUES ('piu-desk-officer','PIU Desk Officer');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM role WHERE slug = 'results-data-design';")
    op.execute("DELETE FROM role WHERE slug = 'piu-desk-officer';")
    # ### end Alembic commands ###
