"""empty message

Revision ID: 35abda43d520
Revises: ac4a76c46e3e
Create Date: 2021-10-14 15:34:01.103280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35abda43d520'
down_revision = 'ac4a76c46e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activitycounterpartfunding") as batch_op:
        batch_op.add_column(sa.Column('required_funding_type', sa.UnicodeText(), nullable=True))
        batch_op.create_unique_constraint('unique_constraint', ['activity_id', 'required_date', 'required_funding_type'])
        batch_op.drop_column('allotted')
        batch_op.drop_column('budgeted')
        batch_op.drop_column('disbursed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activitycounterpartfunding") as batch_op:
        batch_op.drop_constraint("unique_constraint")
        batch_op.create_unique_constraint('unique_constraint', ['activity_id', 'required_date'])
        batch_op.add_column(sa.Column('disbursed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('budgeted', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('allotted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('required_funding_type')
    # ### end Alembic commands ###
