"""empty message

Revision ID: 41e042cbfde4
Revises: 80e18e9f01ea
Create Date: 2019-08-12 19:15:46.243069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e042cbfde4'
down_revision = '80e18e9f01ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activitylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.UnicodeText(), nullable=True),
    sa.Column('target', sa.UnicodeText(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.UnicodeText(), nullable=True),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['maediuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activitylog_activity_id'), 'activitylog', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activitylog_user_id'), 'activitylog', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activitylog_user_id'), table_name='activitylog')
    op.drop_index(op.f('ix_activitylog_activity_id'), table_name='activitylog')
    op.drop_table('activitylog')
    # ### end Alembic commands ###
