"""empty message

Revision ID: 536f20fa2e32
Revises: e16f23f9b2ee
Create Date: 2022-03-20 22:34:51.127459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536f20fa2e32'
down_revision = 'e16f23f9b2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activitydocumentlink") as batch_op:
        batch_op.add_column(sa.Column('filename', sa.UnicodeText(), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.UnicodeText(), nullable=True))
        batch_op.add_column(sa.Column('local', sa.Boolean(), nullable=False,
            server_default='0', default=0))
        batch_op.add_column(sa.Column('filesize', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('saved_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activitydocumentlink") as batch_op:
        batch_op.drop_column('local')
        batch_op.drop_column('filename')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('filesize')
        batch_op.drop_column('saved_datetime')
    # ### end Alembic commands ###
