"""empty message

Revision ID: 5540ee4ec9e3
Revises: 35abda43d520
Create Date: 2021-11-03 16:26:42.573369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5540ee4ec9e3'
down_revision = '35abda43d520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_connection_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.UnicodeText(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('project_code', sa.UnicodeText(), nullable=False),
    sa.Column('project_title', sa.UnicodeText(), nullable=False),
    sa.Column('loan_number', sa.UnicodeText(), nullable=False),
    sa.Column('loan_currency', sa.UnicodeText(), nullable=False),
    sa.Column('grant_loan', sa.UnicodeText(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(precision=2), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_date', 'project_code', 'loan_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_connection_data')
    # ### end Alembic commands ###
