"""empty message

Revision ID: 554f6cbae0ce
Revises: b0d37fb02015
Create Date: 2020-10-22 17:33:42.364167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554f6cbae0ce'
down_revision = 'b0d37fb02015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_marker',
    sa.Column('code', sa.UnicodeText(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('activity_policy_marker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('significance', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('policy_marker_code', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['policy_marker_code'], ['policy_marker.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'policy_marker_code', name='unique_activity_policy_marker_code')
    )
    op.execute("INSERT INTO policy_marker (code, name) VALUES (1,'Gender Equality');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_policy_marker')
    op.drop_table('policy_marker')
    # ### end Alembic commands ###
