"""empty message

Revision ID: 613aa1ee10a8
Revises: cb4e7d805d92
Create Date: 2021-08-10 11:19:54.074531

"""
from alembic import op
import sqlalchemy as sa
from flask import current_app


# revision identifiers, used by Alembic.
revision = '613aa1ee10a8'
down_revision = 'cb4e7d805d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscal_year_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('num_quarters', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    earliest_date = str(current_app.config['EARLIEST_DATE'])
    latest_date = str(current_app.config['LATEST_DATE'])
    op.execute(f"INSERT INTO fiscal_year_choice (start_date, end_date, num_quarters) VALUES ('{earliest_date}','{latest_date}',4);")

    op.create_table('fiscal_year',
    sa.Column('id', sa.UnicodeText(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('num_quarters', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('fiscal_period',
    sa.Column('id', sa.UnicodeText(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_year.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fiscal_year_choice')
    op.drop_table('fiscal_period')
    op.drop_table('fiscal_year')
    # ### end Alembic commands ###
