"""empty message

Revision ID: 6526a8ddff19
Revises: 28cc66cf9810
Create Date: 2019-08-25 21:25:28.420635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6526a8ddff19'
down_revision = '28cc66cf9810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.UnicodeText(), nullable=True),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.Column('finance_type', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_source_code'), 'fund_source', ['code'], unique=True)
    with op.batch_alter_table("activityfinances") as batch_op:
        batch_op.add_column(sa.Column('fund_source_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_activityfinances_fund_source', 'fund_source', ['fund_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activityfinances") as batch_op:
        batch_op.drop_column('fund_source_id')
        batch_op.drop_constraint('fk_activityfinances_fund_source')
    op.drop_table('fund_source')
    # ### end Alembic commands ###
