"""empty message

Revision ID: 91c810ce1b2c
Revises: 6ea3a7ea6ee4
Create Date: 2019-08-24 22:34:56.096522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c810ce1b2c'
down_revision = '6ea3a7ea6ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activityresult") as batch_op:
        batch_op.add_column(sa.Column('source', sa.Integer(), nullable=True))
    with op.batch_alter_table("activityresultindicator") as batch_op:
        batch_op.add_column(sa.Column('measurement_type', sa.UnicodeText(), nullable=True))
        batch_op.add_column(sa.Column('measurement_unit_type', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activityresultindicator") as batch_op:
        batch_op.drop_column('measurement_unit_type')
        batch_op.drop_column('measurement_type')
    with op.batch_alter_table("activityresult") as batch_op:
        batch_op.drop_column('source')
    # ### end Alembic commands ###
