"""empty message

Revision ID: 9f9c35ccc7af
Revises: 33302296b8d5
Create Date: 2020-08-31 15:40:18.557273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9c35ccc7af'
down_revision = '33302296b8d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('icon_class', sa.UnicodeText(), nullable=False, server_default=""))
    op.add_column('response', sa.Column('colour', sa.UnicodeText(), nullable=False, server_default=""))
    op.execute("UPDATE response SET icon_class='fa', icon='check-circle', colour='text-muted' WHERE icon='fa fa-check-circle text-muted';")
    op.execute("UPDATE response SET icon_class='far', icon='check-circle', colour='text-success' WHERE icon='far fa-check-circle text-success';")
    op.execute("UPDATE response SET icon_class='fa', icon='check-circle', colour='text-success' WHERE icon='fa fa-check-circle text-success';")
    op.execute("UPDATE response SET icon_class='fa', icon='exclamation-circle', colour='text-danger' WHERE icon='fa fa-exclamation-circle text-danger';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE response SET icon='fa fa-check-circle text-muted' WHERE icon_class='fa' AND icon='check-circle' AND colour='text-muted';")
    op.execute("UPDATE response SET icon='far fa-check-circle text-success' WHERE icon_class='far' AND icon='check-circle' AND colour='text-success';")
    op.execute("UPDATE response SET icon='fa fa-check-circle text-success' WHERE icon_class='fa' AND icon='check-circle' AND colour='text-success';")
    op.execute("UPDATE response SET icon='fa fa-exclamation-circle text-danger' WHERE icon_class='fa' AND icon='exclamation-circle' AND colour='text-danger';")
    op.drop_column('response', 'icon_class')
    op.drop_column('response', 'colour')
    # ### end Alembic commands ###
