"""empty message

Revision ID: b0d37fb02015
Revises: 9f9c35ccc7af
Create Date: 2020-10-19 13:18:15.786962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d37fb02015'
down_revision = '9f9c35ccc7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity") as batch_op:
        batch_op.add_column(sa.Column('iati_identifier', sa.UnicodeText(), nullable=True))
        batch_op.add_column(sa.Column('objectives', sa.UnicodeText(), nullable=True))
        batch_op.add_column(sa.Column('deliverables', sa.UnicodeText(), nullable=True))
        batch_op.add_column(sa.Column('papd_alignment', sa.UnicodeText(), nullable=True))
    op.execute("UPDATE activity SET iati_identifier=code WHERE domestic_external='external';")
    op.execute("UPDATE activity SET code=null WHERE domestic_external='external';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE activity SET code=iati_identifier WHERE domestic_external='external';")
    with op.batch_alter_table("activity") as batch_op:
        batch_op.drop_column('iati_identifier')
        batch_op.drop_column('objectives')
        batch_op.drop_column('deliverables')
        batch_op.drop_column('papd_alignment')
    # ### end Alembic commands ###
