"""empty message

Revision ID: cb4e7d805d92
Revises: 554f6cbae0ce
Create Date: 2021-03-15 15:10:53.458715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4e7d805d92'
down_revision = '554f6cbae0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_iati_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'field', name='activity_id_field_constraint')
    )
    op.create_index(op.f('ix_activity_iati_preference_field'), 'activity_iati_preference', ['field'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_iati_preference_field'), table_name='activity_iati_preference')
    op.drop_table('activity_iati_preference')
    # ### end Alembic commands ###
