"""empty message

Revision ID: e16f23f9b2ee
Revises: 5540ee4ec9e3
Create Date: 2021-11-12 09:38:31.820427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16f23f9b2ee'
down_revision = '5540ee4ec9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity") as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity") as batch_op:
        batch_op.drop_column('published')
    # ### end Alembic commands ###
