"""empty message

Revision ID: ed668c6d41ed
Revises: 249fc39ee89f
Create Date: 2019-03-26 20:14:16.810744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed668c6d41ed'
down_revision = '249fc39ee89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activitycounterpartfunding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('required_value', sa.Float(precision=2), nullable=True),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('budgeted', sa.Boolean(), nullable=True),
    sa.Column('allotted', sa.Boolean(), nullable=True),
    sa.Column('disbursed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'required_date')
    )
    op.create_index(op.f('ix_activitycounterpartfunding_activity_id'), 'activitycounterpartfunding', ['activity_id'], unique=False)
    op.create_unique_constraint(None, 'forwardspend', ['activity_id', 'period_start_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forwardspend', type_='unique')
    op.drop_index(op.f('ix_activitycounterpartfunding_activity_id'), table_name='activitycounterpartfunding')
    op.drop_table('activitycounterpartfunding')
    # ### end Alembic commands ###
