"""empty message

Revision ID: f5799f295477
Revises: 2910cdc38aaf
Create Date: 2019-08-01 22:44:55.366031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5799f295477'
down_revision = '2910cdc38aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exchangerate") as batch_op:
        batch_op.create_unique_constraint('unique_exchange_rate', ['exchangeratesource_id', 'currency_code', 'rate_date'])
    with op.batch_alter_table("forwardspend") as batch_op:
        batch_op.create_unique_constraint('forward_spend_constraint', ['activity_id', 'period_start_date'])
        batch_op.drop_constraint(u'activity_id__period_start_date', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forwardspend") as batch_op:
        batch_op.create_unique_constraint(u'activity_id__period_start_date', ['activity_id', 'period_start_date'])
        batch_op.drop_constraint('forward_spend_constraint', type_='unique')
    with op.batch_alter_table("exchangerate") as batch_op:
        batch_op.drop_constraint('unique_exchange_rate', type_='unique')
    # ### end Alembic commands ###
