# -*- coding: UTF-8 -*-

headers = ['Reporting Organisation', u'Standard activity identifier', 
u'Other activity identifiers', u'Activity Title', 
u"Activity Title (in recipient's language)", u'Activity Description', 
u"Activity Description (in recipient's language)", u'Activity Status', 
u'Activity Dates (Start Date)', u'Activity Dates (End Date)', 
u'Activity Contacts', u'Participating Organisation (Funding)', 
u'Participating Organisation (Implementing)', u'Recipient Country', 
u'Recipient Region', u'Sub-national Geographic Location - Latitude', 
u'Sub-national Geographic Location - Longitude', u'Sector (DAC CRS)', 
u'Sector (Agency specific)', u'Policy Markers', u'Collaboration Type', 
u'Default Flow Type', u'Default Finance Type', u'Default Aid Type', 
u'Default Tied Aid Status', u'Activity Budget', u'Planned Disbursements', 
u'Financial transaction (Commitment)', 
u'Financial transaction (Disbursement & Expenditure)', 
u'Financial transaction (Reimbursement)', 
u'Financial transaction (Incoming Funds)', 
u'Financial transaction (Loan repayment / interest repayment)', 
u'Activity Documents', u'Activity Website', u'Related Activity', 
u'Conditions attached Y/N', u'Text of Conditions', u'Results data', 
u'Cofinancement', u'Date de mise à jour du projet', 
u'Date de la dernière publication', u'Date de publication NCO', 
u'CRG']

fr_headers = ["Société", u"Id. Concours", u"Id. Projet", 
u"Nom du projet pour les instances", u"Non applicable", 
u"Description du projet", u"Non applicable", u"Etat du projet", 
u"Date de 1er versement (projet)", 
u"Date d’achèvement opérationnel du projet", u"Libellé agence", 
u"Valeur fixe", u"Libellé bénéficiaire primaire", 
u"Pays de réalisation", u"Région", u"Latitude", u"Longitude ", 
u"Libellé secteur économique  (CAD-5)", u"Libellé CICID", 
u"Non applicable", u"Valeur fixe", u"Libellé indicateur APD", 
u"Groupe de produit", u"Valeur fixe", u"Valeur fixe", 
u"Engagements bruts (euro)", u"Non applicable", u"Non applicable", 
u"Versements (euro)", u"Non applicable", u"Non applicable", 
u"Non applicable", u"Lien_Fiche_Projet", u"Non applicable", 
u"Non applicable", u"Non applicable", u"Non applicable", 
u"Non applicable", u"Cofinanciers (O/N)", 
u"Date mise à jour données projet", u"Date de la dernière publication", 
u"Date de publication NCO", u"CRG"]